### PR TITLE
Support both Helm 2 and 3

### PR DESCRIPTION
**Pull request by mrooding**
### What changes were proposed in this pull request?
I've added support for both Helm v2 and v3 as proposed in #31

- I've moved all Helm 2 related bash functions from `tiller.sh` to `helm2.sh`
- I've introduced a `HELM_TIMEOUT` env var since Helm 3 changed how the `--timeout` flag is to be used. 
- Helm 3 also changed the output of `helm version`. The init script that I've added supports both and has an else case for when no version can be detected.
- I've removed the tiller check at the start of `shared.sh`. When using `install-gke.sh` the status of either Helm 2 or 3 is verified. The only use case where the additional check in `shared.sh` made sense if someone was to execute `gke-install-cloudflow.sh` directly. If you want, I can add a check to `shared.sh` to verify either Helm 2 or 3.
- I've generalised the Chart used for testing the installation from `tiller-test-chart` to `helm-test-chart` and applied it to verify both the Helm 2 and 3 installation.

### Why are the changes needed?
To support users that have Helm v3 installed

### Does this PR introduce any user-facing change?
Yes, it will allow users with both Helm v2 and v3 to use the GCP installer

### How was this patch tested?
I've tested the installation on a GCP cluster with both Helm v2 and v3

### CODE REVIEW

**Comment by skonto** [comment]
thank you @mrooding, awesome!

**Comment by skyluc** [comment]
FYI: the `uninstall-cloudflow.sh` script also need to be updated to support Helm 3.
The `helm delete` command doesn`t have a `--purge` option anymore. `purge` is the default behavior on Helm 3.

**Comment by mrooding** [comment]
> FYI: the `uninstall-cloudflow.sh` script also need to be updated to support Helm 3.
> The `helm delete` command doesn`t have a `--purge`option anymore.`purge` is the default behavior on Helm 3.

Thank you for mentioning this. I've added support for both version in the uninstaller in the latest commit.

**Comment by debasishg** [comment]
@mrooding This may take some time to 👀 .. we have a holidays shutdown till Jan 1, 2020.

**Comment by mrooding** [comment]
@debasishg no problem. Enjoy the holidays!

**Comment by yuchaoran2011** [comment]
@mrooding Thanks again for the PR. It LGTM. We are discussing Helm 3 migration strategy internally within the team. In the meantime, could you please update the PR to resolve the conflicts. We'll merge when ready.

**Comment by yuchaoran2011** [comment]
@mrooding We have decided to support both Helm 2 and 3 binaries in Cloudflow as you implemented in this PR. Could you resolve the conflicts and then we'll merge?

**Comment by mrooding** [comment]
@yuchaoran2011 I've just rebased on top of master.

**Pull request merged**
