### PR TITLE
runLocal in Test scope

### PR DESCRIPTION
**Pull request by RayRoestenburg**
### What changes were proposed in this pull request?

Fix for #620 

### Why are the changes needed?

Runtime scoped dependencies end up in /opt/cloudflow

### How was this patch tested?

GKE and local

### CODE REVIEW

**Review by ennru — APPROVED** [review]
LGTM.

**Comment by maasg** [comment]
Finally % Test  :-)

**Comment by RayRoestenburg** [comment]
@maasg LOL! yes and funny enough just running `runLocal` just works, which I did not expect, but hey I'm not a Gandalf level sbt wizard.. ;-)

**Comment by echang0929** [comment]
@RayRoestenburg Still I have this issue:
`
➜ kubectl logs sensor-data-scala-http-ingress-5f66674f59-qxtnh -n sensor-data-scala
Cloudflow Runner
Java opts: -javaagent:/prometheus/jmx_prometheus_javaagent.jar=2050:/etc/cloudflow-runner/prometheus.yaml -XX:MaxRAMPercentage=50.0 -Djdk.nio.maxCachedBufferSize=1048576
Classpath: /etc/cloudflow-runner:/opt/cloudflow/*
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/cloudflow/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/cloudflow/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
log4j:WARN No appenders could be found for logger (cloudflow.runner.Runner$).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Loading application.conf from: /etc/cloudflow-runner/application.conf, secret config from: /etc/cloudflow-runner-secret/secret.conf
`
I deployed cloudflow 2.0.10 with helm chart, so has this fix not been released?

**Pull request merged**
