### PR TITLE
Removing schema from cr

### PR DESCRIPTION
**Pull request by franciscolopezsancho**
### What changes were proposed in this pull request?
#986
CloudflowApplication size reach etcd request size limit

### Why are the changes needed?
the CR json hits the limit of etcd

### Does this PR introduce any user-facing change?
no

### How was this patch tested?
unit testing and in GKE cluster checking the console enterprise was working fine.

### CODE REVIEW

**Comment by andreaTP** [comment]
🎉  love this! We have to coordinate when we merge but is not going to be a big issue.
Have you considered using a different `case class` here:
https://github.com/lightbend/cloudflow/blob/7988d1b3085d97e3f5c31d73c45f4da8d3417373/core/cloudflow-blueprint/src/main/scala/cloudflow/blueprint/deployment/ApplicationDescriptor.scala#L114
to make sure at compile time that this property is not used?

**Comment by franciscolopezsancho** [comment]
:) Thanks @andreaTP! I did consider removing the schema parameter inside that class but it's used to compare inlets and outlets, I found. We can talk about it at any time.

**Review by RayRoestenburg — APPROVED** [review]

**Comment by RayRoestenburg** [comment]
@andreaTP @franciscolopezsancho please coordinate to have this merged (possibly after the big changes in operator)?

**Comment by franciscolopezsancho** [comment]
merging with fabric8-action-next

**Pull request closed without merging**
