### PR TITLE
Remove magnolia

### PR DESCRIPTION
**Pull request by andreaTP**
Ref: https://github.com/scala-open-letter/scala-open-letter.github.io

### CODE REVIEW

**Comment by SethTisue** [comment]
LGTM (and I'm glad it appears to be that easy), but I see CI isn't quite on board yet.

**Comment by SethTisue** [comment]
Have you measured any impact on compile times? That's typically been the hook for projects to adopt Magnolia, is decreased compile times.

**Comment by andreaTP** [comment]
@SethTisue I just forgot to make the necessary changes into an auxiliary project, nothing major.

Yes, the compilation time will basically double on the cloudflow-config subproject but it doesn't spill to users in any way and, locally, the cache works well.

**Review by debasishg — APPROVED** [review]
LGTM

**Pull request merged**
