### PR TITLE
Fix compilation warnings #10

### PR DESCRIPTION
**Pull request by mrooding**
Removed several compilation warnings as indicated in #10

* Removed unused import
* Removed unused portMapping parameter

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by debasishg** [comment]
Hello @mrooding - Thanks for the PR. Will u please sign the CLA so that the PR can be merged ?

**Comment by mrooding** [comment]
Hi @debasishg 

I've done so this morning. I've received confirmation by e-mail from Lightbend that it was signed:

```Thank you for signing the Lightbend CLA.

If you have already sent a pull request please add a comment to the pull request saying you did sign the CLA.

We are looking forward to your contributions!

The Lightbend Team
email: ...
lightbend.com```

**Comment by mrooding** [comment]
I just signed it again and that seemed to resolve the CLA check for the 2 other PRs I've just created.

**Comment by agemooij** [comment]
Thanks @mrooding ! Long time no see 😉

**Comment by mrooding** [comment]
Indeed @agemooij!

**Comment by RayRoestenburg** [comment]
I recognised you in the crowd @mrooding ;-) thanks for the PR!

**Pull request merged**
