### PR TITLE
Flink 1.13-SNAPSHOT

### PR DESCRIPTION
**Pull request by RayRoestenburg**
### What changes were proposed in this pull request?

Draft PR to try out Flink 1.13-SNAPSHOT

### CODE REVIEW

**Comment by Lockdain** [comment]
My heart stop beating when I see this PR!
Does it means that Cloudflow will be bumped to Flink 1.13 with native K8s support?

**Comment by RayRoestenburg** [comment]
Hi @Lockdain, yes we are working on an *experimental* feature for supporting Flink 1.13 with native K9s support... :-)

**Comment by Lockdain** [comment]
> Hi @Lockdain, yes we are working on an _experimental_ feature for supporting Flink 1.13 with native K9s support... :-)

Sounds great!
Does it mean that Apache Flink remains interesting for Lightbend as part of Cloudflow?

**Comment by RayRoestenburg** [comment]
@Lockdain That's a very broadly formulated question ;-) Let's just say for now that we are experimenting with integration patterns.

**Comment by RayRoestenburg** [comment]
Closing this draft for now, this code will be moved.

**Pull request closed without merging**
