### PR TITLE
Fix to report streamlet scanning errors

### PR DESCRIPTION
**Pull request by RayRoestenburg**
### What changes were proposed in this pull request?

The sbt plugin keeps track of the problems found scanning for streamlets and provides these as problems on the blueprint.

### Why are the changes needed?

User reported issue, a Streamlet used the StreamletContext from outside of the logic, which means that the Streamlet cannot be constructed for extracting the streamlet. 

This results in feedback during verification of blueprint that is confusing:
```[error] ClassName sensordata.ValidMetricLogger for valid-logger cannot be found.```

The cause was missing, which is:
```
[error] Streamlet 'sensordata.ValidMetricLogger' could not be instantiated for introspection. Its constructor threw an StreamletContextException: StreamletContext can only be accessed from the `createLogic()` method.
```
### Does this PR introduce any user-facing change?

The type of the `allStreamletDescriptorsByProject` taskKey has been changed (which users should usually not need to use directly)

### How was this patch tested?

Tested with an example project, and current unit tests for scanning for streamlets.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by RayRoestenburg** [comment]
wow I must have changed something in my github user settings lol 
image

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Review by andreaTP — APPROVED** [review]

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Pull request merged**
