### PR TITLE
Fixed status of KafkaTopic

### PR DESCRIPTION
**Pull request by yuchaoran2011**
Fixed status fields based on Strimzi code: https://strimzi.io/docs/master/#type-KafkaTopicStatus-reference. Tested with call record aggregator.

### CODE REVIEW

**Comment by RayRoestenburg** [comment]
@yuchaoran2011 it would be great to test this on a cluster and actually see some of these statuses printed out somewhere, did you try that?

**Comment by skyluc** [comment]
Test call-record-aggregator with this change. The operator works correctly.

**Comment by skyluc** [comment]
Does that look like the status message we expect ?
```
status:
  app_id: luc-call-record-aggregator
  app_version: 1-6a4cfbb
  streamlet_statuses:
  - pod_statuses:
    - name: luc-call-record-aggregator-console-egress-6fbb76ddbd-wr66b
      ready: "True"
      restarts: 2
      status: Running
    streamlet_name: console-egress
  - pod_statuses:
    - name: luc-call-record-aggregator-cdr-ingress-7b6c7877cb-h4dln
      ready: "True"
      restarts: 0
      status: Running
    streamlet_name: cdr-ingress
  - pod_statuses:
    - name: luc-call-record-aggregator-cdr-generator1-1583166687766-exec-1
      ready: "True"
      restarts: 0
      status: Running
    - name: luc-call-record-aggregator-cdr-generator1-1583166687766-exec-2
      ready: "True"
      restarts: 0
      status: Running
    - name: luc-call-record-aggregator-cdr-generator1-driver
      ready: "True"
      restarts: 0
      status: Running
    streamlet_name: cdr-generator1
  - pod_statuses:
    - name: luc-call-record-aggregator-error-egress-64f54c5dcb-gdsf9
      ready: "True"
      restarts: 0
      status: Running
    streamlet_name: error-egress
  - pod_statuses:
    - name: luc-call-record-aggregator-merge-69f676f4b8-5c7s9
      ready: "True"
      restarts: 0
      status: Running
    streamlet_name: merge
  - pod_statuses:
    - name: luc-call-record-aggregator-cdr-aggregator-driver
      ready: "True"
      restarts: 0
      status: Running
    - name: luc-call-record-aggregator-cdr-aggregator-1583166688157-exec-2
      ready: "True"
      restarts: 0
      status: Running
    - name: luc-call-record-aggregator-cdr-aggregator-1583166688157-exec-1
      ready: "True"
      restarts: 0
      status: Running
    streamlet_name: cdr-aggregator
  - pod_statuses:
    - name: luc-call-record-aggregator-cdr-generator2-1583166687478-exec-1
      ready: "True"
      restarts: 0
      status: Running
    - name: luc-call-record-aggregator-cdr-generator2-1583166687478-exec-2
      ready: "True"
      restarts: 0
      status: Running
    - name: luc-call-record-aggregator-cdr-generator2-driver
      ready: "True"
      restarts: 0
      status: Running
    streamlet_name: cdr-generator2
```

**Comment by yuchaoran2011** [comment]
@RayRoestenburg Yes. An example output is:
```
Status:
  Conditions:
    Last Transition Time:  2020-03-02T16:59:22.769Z
    Status:                True
    Type:                  Ready
  Observed Generation:     1
```
@skyluc Thanks for testing!

**Pull request merged**
