### PR TITLE
cloudsmith get.sh script

### PR DESCRIPTION
**Pull request by andreaTP**
This is what is needed to go into production with Cloudsmith + Proxy.
Waiting for nudges from @sebastian-alfers and @JustinPihony

### CODE REVIEW

**Comment by RayRoestenburg** [comment]
LGTM, I mean, I can't validate those URLs, but seems ok.

**Comment by andreaTP** [comment]
@JustinPihony this already has the final proxy.
@sebastian-alfers as soon as the packages a synced let me know so that I can merge 😄

**Comment by JustinPihony** [comment]
LGTM, and will defer to Sebastian about any syncing. As far as I am aware everything you need should be in place, though.

**Comment by andreaTP** [comment]
Not yet ready:
e.g. binaries for `2.0.24` are not there

**Review by RayRoestenburg — APPROVED** [review]

**Comment by sebastian-alfers** [comment]
Sorry for the delay, I synced the missing files - including `2.0.24` as you can see [here](https://cloudsmith.io/~lightbend/repos/cloudflow-cli/packages/?q=2.0.24&sort=-version) ;)

**Pull request merged**
