### PR TITLE
Use sbt 1.5

### PR DESCRIPTION
**Pull request by marcospereira**
### What changes were proposed in this pull request?

Update sbt version to 1.5.5 and use its new slash syntax.

### Does this PR introduce any user-facing change?

No.

### CODE REVIEW

**Comment by RayRoestenburg** [comment]
@marcospereira Looking at it again, the currently deprecated, but still existing `cloudflow-spark` library depends on Spark 2.4.5. The new cloudflow-contrib library depends on Spark 3.1.2. `sparksql-scalapb` has specific versions for both of these Spark versions, the version in this PR is for Spark 3.x. Once we remove cloudflow-spark completely, in `3.x`, we can remove these dependencies. I guess in the meantime we will have to deal with some eviction errors.

**Comment by marcospereira** [comment]
> I guess in the meantime we will have to deal with some eviction errors, and not update the sparksql-scalapb support, since otherwise the deprecated support will not work.

I will take a look at it later because what the eviction is doing is basically warning us that the newer version is used instead of what is declared by Spark 2.4.5. Meaning that, in the end, we may need to instead do some dependencies override.

**Comment by RayRoestenburg** [comment]
@marcospereira yes that sounds like a solution. (though it has to work such that if you use cloudflow-contrib, it overrides it with the spark 3.1.2 compatible libs, of course)

**Comment by ennru** [comment]
Superseded by #1115 AFAICS

**Pull request closed without merging**
