### PR TITLE
adding container ports to akka streamlet through configuration, annotations for akka, spark and flink.

### PR DESCRIPTION
**Pull request by franciscolopezsancho**
### What changes were proposed in this pull request?
adding remote debug capability 

### Why are the changes needed?
UX

### Does this PR introduce any user-facing change?
yes, the user can attach a debugger

### How was this patch tested?
adding the pertinent configuration and adding breaking points into IntelliJ. Done for all the base images. Breaking points behaved as usual.

### CODE REVIEW

**Comment by RayRoestenburg** [comment]
It's interesting that the Flink CR and Spark CR have no ability to add container ports to the container.
@franciscolopezsancho this could still be interesting for akka, so you can at least provide the info that you are going to expose a port. But as discussed for debugging purposes we don't need this addition. 

For other readers: It's interesting that container ports on container is only for information purposes:

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#container-v1-core

```
List of ports to expose from the container. Exposing a port here gives the system additional information about the network connections a container uses, but is primarily informational. Not specifying a port here DOES NOT prevent that port from being exposed. Any port which is listening on the default "0.0.0.0" address inside a container will be accessible from the network. Cannot be updated.
```

**Review by RayRoestenburg — COMMENTED** [review]
As discussed probably not needed.

**Comment by franciscolopezsancho** [comment]
Do you think @RayRoestenburg  we should add this info in the docs?

**Comment by RayRoestenburg** [comment]
@franciscolopezsancho no, those are kubernetes details I would say.

**Comment by RayRoestenburg** [comment]
RE-opening this since we need this, and nice to add annotations too, for adding ports for prometheus to scrape.

**Review by andreaTP — APPROVED** [review]

**Review by andreaTP — COMMENTED** [review]
A couple of questions but in general looks good

**Pull request merged**
